### ISSUE TITLE
zone.list_resource_record_sets example in index.rst is wrong

### ISSUE THREAD

**Issue by allanlw** [googleapis/python-dns#15]
In index.rst, there is the following example:

``` lang:python
>>> records, page_token = zone.list_resource_record_sets()  # API request
>>> while page_token is not None:
...     next_batch, page_token = zone.list_resource_record_sets(
...         page_token=page_token)  # API request
...     records.extend(next_batch)
```

However, zone.list_resource_record_sets only returns only one value and I guess does the paging automatically.

**Comment by busunkim96** [comment]
Thanks for filing an issue! It looks like those samples are out of date. See https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/dns/api for tested samples.
