### ISSUE TITLE
README.md is outdated

### ISSUE THREAD

**Issue by fguendling** [googleapis/python-dns#176]
It says

`Code samples and snippets live in the samples/ folder.`

but there is no `samples` folder

**Comment by vam-google** [comment]
Hi @fguendling,
I updated the README to link to the closest thing I could find for samples (https://github.com/googleapis/python-dns/pull/177).

I'm not sure how well maintained and up to date those samples, but they at least seem to be following the latest version of each client, so they could be good enough.

**Comment by vam-google** [comment]
Hm... Apparently those readmes are autogenerated, and manual changes are getting overwritten. Either way, please look for samples in https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/dns/api
