### ISSUE TITLE
client.quotas() error

### ISSUE THREAD

**Issue by tmegow** [googleapis/python-dns#21]
- OS type and version: `macOS Mojave (10.14.6 (18G5033))`
  - Python version: `Python 3.7.4`
  - pip version: `pip 20.2.3 from /Users/thadmegow/dev/google-cloud-dns/.venv/lib/python3.7/site-packages/pip (python 3.7)`
  - `google-cloud-dns` version: 
```Name: google-cloud-dns
Version: 0.32.0
Summary: Google Cloud DNS API client library
Home-page: https://github.com/googleapis/python-dns
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/thadmegow/dev/google-cloud-dns/.venv/lib/python3.7/site-packages
Requires: google-cloud-core
Required-by:
```

#### Steps to reproduce

  1. Ensure authentication is properly setup (I'm using a Service Account)
  2. Execute code below, substituting "my-project" for a valid projectID

#### Code example

```python
from google.cloud import dns
client = dns.Client(project="my-project")
quotas = client.quotas()  # API request
```
![image](https://user-images.githubusercontent.com/10726968/93358730-d631b080-f80f-11ea-8136-018cbee64fce.png)

#### Stack trace
```
Traceback (most recent call last):
  File "google-cloud-dns-search.py", line 3, in <module>
    quotas = client.quotas()  # API request
  File "/Users/thadmegow/dev/google-cloud-dns/.venv/lib/python3.7/site-packages/google/cloud/dns/client.py", line 100, in quotas
    key: int(value) for key, value in resp["quota"].items() if key != "kind"
  File "/Users/thadmegow/dev/google-cloud-dns/.venv/lib/python3.7/site-packages/google/cloud/dns/client.py", line 100, in <dictcomp>
    key: int(value) for key, value in resp["quota"].items() if key != "kind"
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```

**Comment by busunkim96** [comment]
I'm able to reproduce this locally.  My theory is that `resp` is borked in some way and the typeerror is from the library attempting to parse it as normal. https://github.com/googleapis/python-dns/blob/51d4d10884d3e13bb9051114537a1a6eddab0086/google/cloud/dns/client.py#L97

@tmegow Do you have information on when this stopped working?

**Comment by tmegow** [comment]
> I'm able to reproduce this locally. My theory is that `resp` is borked in some way and the typeerror is from the library attempting to parse it as normal.
> 
> https://github.com/googleapis/python-dns/blob/51d4d10884d3e13bb9051114537a1a6eddab0086/google/cloud/dns/client.py#L97
> 
> @tmegow Do you have information on when this stopped working?

Thank you for investigating! Unfortunately, no I don't have any more contextual info.

**Comment by busunkim96** [comment]
The `quota` resource object has a new field `whitelistedKeySpecs` which is a list of dictionaries. Will open a PR to update the logic shortly.

https://cloud.google.com/dns/docs/reference/v1/projects#resource

```
{
  "kind": "dns#project",
  "number": unsigned long,
  "id": string,
  "quota": {
    "kind": "dns#quota",
    "managedZones": integer,
    "rrsetsPerManagedZone": integer,
    "rrsetAdditionsPerChange": integer,
    "rrsetDeletionsPerChange": integer,
    "totalRrdataSizePerChange": integer,
    "resourceRecordsPerRrset": integer,
    "dnsKeysPerManagedZone": integer,
    "whitelistedKeySpecs": [
      {
        "kind": "dns#dnsKeySpec",
        "keyType": string,
        "algorithm": string,
        "keyLength": unsigned integer
      }
    ],
    "networksPerManagedZone": integer,
    "managedZonesPerNetwork": integer,
    "policies": integer,
    "networksPerPolicy": integer,
    "targetNameServersPerPolicy": integer,
    "targetNameServersPerManagedZone": integer
  }
}
```

**Comment by tmegow** [comment]
thank you!

**Comment by busunkim96** [comment]
@tmegow Of course, thank you for your patience! The library will be released on Monday with the fix.
