### ISSUE TITLE
Missing optional parameter 'dnssec' 

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-dns#32]
https://cloud.google.com/dns/docs/dnssec-config#creating

**Comment by JustinBeckwith** [comment]
In a comical backwards series of events, I just brought this forward to fix the overground bug https://github.com/googleapis/nodejs-dns/pull/439

**Comment by busunkim96** [comment]
@JustinBeckwith Was it fairly easy to just add this parameter in the NodeJS library? I'm dDebating whether I should attempt to add this now or wait for REGAPIC.

**Comment by JustinBeckwith** [comment]
Yeah this was super easy to add

**Comment by parthea** [comment]
@busunkim96  Please can you take a look?

**Comment by busunkim96** [comment]
Thanks @JustinBeckwith, I agree this is a feature request. Given DIREGAPIC is imminent, I'm going to continue to punt on this. The last time I looked into this the current client was different enough from the API that adding this wasn't a one line parameter drop in.
